CREATE TABLE IF NOT EXISTS mpa_ratings (
     mpa_rating_id INT PRIMARY KEY,
     name VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS genres (
     genre_id INT PRIMARY KEY,
     name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS users (
     user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     email VARCHAR(255) NOT NULL,
     login VARCHAR(255) NOT NULL,
     name VARCHAR(255),
     birthday DATE
);

CREATE TABLE  IF NOT EXISTS films (
     film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     title VARCHAR(255) NOT NULL,
     description VARCHAR(200),
     release_date DATE,
     duration INT,
     mpa_rating_id INT,
     FOREIGN KEY (mpa_rating_id) REFERENCES mpa_ratings(mpa_rating_id)
);

CREATE TABLE IF NOT EXISTS film_genres (
     film_id BIGINT REFERENCES films(film_id),
     genre_id INT REFERENCES genres(genre_id),
     PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
     film_id BIGINT REFERENCES films(film_id),
     user_id BIGINT REFERENCES users(user_id),
     PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friendships (
     user_id BIGINT REFERENCES users(user_id),
     friend_id BIGINT REFERENCES users(user_id),
     PRIMARY KEY (user_id, friend_id)
);

